#%RAML 1.0 ResourceType

is: [client_id_secret, error_respond, 500error_respond]
get?:
  displayName: Get <<target_name>> by <<target_key_get>>
  responses:
    200:
      body:
        application/json:
          type: <<response_body_get>>

post?:
  displayName: Create <<target_name>>
  body:
    application/json:
      type: <<request_body_post>>
  responses:
    "200":
      body:
        application/json:
          type: <<response_body_post>>

put?:
  displayName: Upsert <<target_name>>
  body:
    application/json:
      type: <<request_body_put>>
  responses:
    "200":
      body:
        application/json:
          type: <<response_body_put>>

delete?:
  displayName: Delete <<target_name>> by <<target_key_delete>>
  responses:
    "200":
      body:
        application/json:
          type: <<response_body_delete>>
