#%RAML 1.0 Library
uses:
  type_lib: exchange_modules/7f6a43c7-2acb-4e80-88b7-26cba0a5cb48/type-lib/1.0.0/type-lib.raml

types:
  string_phone:
    type: string
    maxLength: 18
    example: 03-123-1234
  string_postal_code:
    type: string
    minLength: 8
    maxLength: 8
    example: 123-1234
  string_corporate_number:
    type: string
    minLength: 13
    maxLength: 13
    example: "1234567890123"
  number_offiecs_number:
    type: number
    minimum: 0
    maximum: 999999999999
    example: 321
  number_emloyers_number:
    type: number
    minimum: 0
    maximum: 999999999999
    example: 123
  string_employment_insurance_applicable_office_num:
    type: string
    minLength: 13
    maxLength: 13
    example: 1234-123456-1
  string_labor_insurance_numer:
    type: string
    minLength: 18
    maxLength: 18
    example: 12-1-12-123456-123
  number_cut_of_date_for_salary:
    type: number
    minimum: 0
    maximum: 99
    example: 11
  number_payday:
    type: number
    minimum: 0
    maximum: 99
    example: 22
  account_object:
    type: object
    properties:
      id:
        type: type_lib.id
        required: false
      name:
        description: name of account
        type: type_lib.string_255
        required: true
        example: 株式会社Pangu
      corporate_number:
        type: string_corporate_number | nil
        required: false
      corporate_scale:
        description: scale of corporate
        type: type_lib.string_255 | nil
        required: false
        example: 大企業
