#%RAML 1.0
title: exp-api

/accounts:
  description: Collection of available accounts in sfdc
  get:
    description: Get a list of accounts based on the accounts name.
    queryParameters:
      industry:
        required: true
        type: string
        example: "IT"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "results": [
                  {
                    "name": "A株式会社",
                    "industry": "IT",
                    "employees": "100"
                    "phone": "080-3333-5555"
                  },
                  {
                    "name": "B株式会社",
                    "Industry": "IT",
                    "employees": "120"
                    "phone": "080-2222-1111"
                  },
                  {
                    "name": "C株式会社",
                    "Industry": "IT",
                    "employees": "140"
                    "phone": "080-5555-7777"
                  }
                ]
              }