#%RAML 1.0 Library
types:
  query_limit:
    description: Number of data returned by request
    type: number
    minimum: 1
    maximum: 100
    defualt: 10
  query_offset:
    description: Number of query offset
    type: number
    minimum: 0
    defualt: 0
    example: 10
  query_sort:
    description: Field to order by
    type: string
    defualt: id
  query_order:
    description: Search Order,ASC for ascending, DESC for descending
    type: string 
    enum:
      - ASC
      - DESC
    default: DESC
    example: DESC

  id:
    description: Key id of target data category
    type: string
    minimum: 18
    maximum: 18
    example: "a0M0w000000iFwYeAU"
  user_id:
    description: User id of user who performed the action
    type: string
    minimum: 18
    maximum: 18
    example: "a0M0w000000iFwYeAU"
  string_255:
    type: string
    maxLength: 255
  date:
    type: date-only
    example: 2021-01-01
  time:
    type: time-only
    example: "09:00:00"
  datetime_with_timezone:
    type: datetime
    example: 2021-01-01T09:00:00:000
  email:
    type: string
    pattern: ^(.+)@(.+)$
    example: mule@gmai.com
